import os

NOKIAHEALTHAPI_CLIENT_ID = os.environ["NOKIAHEALTHAPI_CLIENT_ID"]
NOKIAHEALTHAPI_CLIENT_SECRET = os.environ["NOKIAHEALTHAPI_CLIENT_SECRET"]

MYAPI_BASICAUTH_USER = os.environ["MYAPI_BASICAUTH_USER"]
MYAPI_BASICAUTH_PASS = os.environ["MYAPI_BASICAUTH_PASS"]